### ISSUE TITLE
[Bug] App crashed after opening

### ISSUE THREAD

**Issue by satarov-ruslan** [LNReader/lnreader#66]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rajarsheechatterjee.LNReader/com.rajarsheechatterjee.LNReader.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
 at android.os.Handler.dispatchMessage(Handler.java)
 at android.os.Looper.loop(Looper.java)
 at android.app.ActivityThread.main(ActivityThread.java)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.swmansion.rnscreens.ScreenFragment: calling Fragment constructor caused an exception
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:566)
 at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
 at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
 at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
 at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
 at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:196)
 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:287)
 at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
 at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:44)
 at com.rajarsheechatterjee.LNReader.MainActivity.onCreate(MainActivity.java:38)
 at android.app.Activity.performCreate(Activity.java)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
 ... 10 more
Caused by: java.lang.reflect.InvocationTargetException
 at java.lang.reflect.Constructor.newInstance0(Native Method)
 at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
 at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
 ... 21 more
Caused by: java.lang.IllegalStateException: Screen fragments should never be restored. Follow instructions from https://github.com/software-mansion/react-native-screens/issues/17#issuecomment-424704067 to properly configure your main activity.
 at com.swmansion.rnscreens.ScreenFragment.<init>(ScreenFragment.java:42)
 ... 24 more
```

**Comment by rajarsheechatterjee** [comment]
Does [this version](https://drive.google.com/file/d/1zoEN7zqDnHoJbFj7jNB-jt7wVo4UjoRw/view?usp=sharing) fix the crash?
